const projects = [
    {
        "title": "Quickers Venture",
        "slug": "quickers-venture",
        "link": "https://quickers.vc/",
        "technology": "Laravel, React.js, Inertia.js, Bootstrap 5",
        "thirdy_party_api":"Stripe, OpenAI, Social Media SDKs, Google cloud, Pusher",
        "platform": "website",
        "company": "Quickers Venture S.L",
        "short_description": "A SaaS platform for Startups to get fundraised, for Investors to invest, for Incubators to incubate ventures.",
        "long_description": "",
        "media": [],
        "thumbnail": "/images/studio-agency/service_img_1.jpeg"
    },
    {
        "title": "Logo Maker",
        "slug": "logo-maker",
        "link": "https://apps.apple.com/us/app/logo-maker-graphic-design/id6478085358",
        "technology": "Flutter, GetX",
        "thirdy_party_api":"Firebase",
        "platform": "iOS",
        "company": "Majestic Studios",
        "short_description": "Logo maker app built using flutter with the help of GetX state management to create logos",
        "long_description": "",
        "media": [],
        "thumbnail": "/images/studio-agency/service_img_1.jpeg"
    },
    {
        "title": "AI ChatBot & Ask Bot Assistant",
        "slug": "ai-chat",
        "link": "https://apps.apple.com/us/app/ai-chatbot-ask-bot-assistant/id6472343525",
        "technology": "Flutter, GetX",
        "thirdy_party_api":"OpenAI, DreamStudio",
        "platform": "macOS",
        "company": "Private client",
        "short_description": "AI ChatBot app and AI Image generator powered by OpenAI and DreamStudio",
        "long_description": "",
        "media": [],
        "thumbnail": "/images/studio-agency/service_img_1.jpeg"
    },
    {
        "title": "Biomarkx",
        "slug": "biomarkx",
        "link": "https://www.biomarkx.com/",
        "technology": "Laravel with RestAPIs",
        "thirdy_party_api":"OpenAI assistant models",
        "platform": "Android, iOS, website",
        "company": "BioMarkX LLC",
        "short_description": "An app for patient/users who seeks help related to their diabetes & metabolic health",
        "long_description": "",
        "media": [],
        "thumbnail": "/images/studio-agency/service_img_1.jpeg"
    },
    {
        "title": "Quick AI",
        "slug": "quick-ai",
        "link": "https://quickers.vc/quick-ai",
        "technology": "Laravel with RestAPIs",
        "thirdy_party_api":"Stripe, OpenAI, Facbook Whatsapp SDK",
        "platform": "website",
        "company": "Quickers Venture S.L",
        "short_description": "A SaaS platform for Startups to get fundraised, for Investors to invest, for Incubators to incubate ventures.",
        "long_description": "",
        "media": [],
        "thumbnail": "/images/studio-agency/service_img_1.jpeg"
    },
    {
        "title": "Quick HR",
        "slug": "quick-hr",
        "link": "https://quickers.vc/quick-hr",
        "technology": "Laravel, React.js, Inertia.js, Bootstrap 5",
        "thirdy_party_api":"Stripe, OpenAI, Social Media SDKs, Google cloud",
        "platform": "website",
        "company": "Quickers Venture S.L",
        "short_description": "A SaaS platform for Startups to get fundraised, for Investors to invest, for Incubators to incubate ventures.",
        "long_description": "",
        "media": [],
        "thumbnail": "/images/studio-agency/service_img_1.jpeg"
    },
    {
        "title": "AI ChatBot Assist & Ask Bot",
        "slug": "assist-ai",
        "link": "https://apps.apple.com/us/app/ai-chatbot-assist-ask-bot/id6466761229",
        "technology": "Flutter, GetX",
        "thirdy_party_api":"OpenAI, DreamStudio, ClipDrop",
        "platform": "Android, iOS, macOS",
        "company": "Personal project",
        "short_description": "AI chatapp app with lots featues AI Chat, AI image generator, AI image background remover, AI content generator powered by OpenAI and DreamStudio",
        "long_description": "",
        "media": [],
        "thumbnail": "/images/studio-agency/service_img_1.jpeg"
    },
    {
        "title": "Label Maker design",
        "slug": "label-maker",
        "link": "https://apps.apple.com/us/app/label-maker-design-creator/id6449620971",
        "technology": "Flutter, GetX",
        "thirdy_party_api":"Firebase",
        "platform": "Android, iOS, macOS",
        "company": "Private project",
        "short_description": "Label maker app built using flutter with the help of GetX state management to craft labels",
        "long_description": "",
        "media": [],
        "thumbnail": "/images/studio-agency/service_img_1.jpeg"
    },
    {
        "title": "Latytude",
        "slug": "latytude",
        "link": "https://latytude.com/",
        "technology": "Laravel, Bootstrap 4",
        "thirdy_party_api":"Social Media SDKs, Google cloud, Google Map",
        "platform": "website",
        "company": "Quickers Venture S.L",
        "short_description": "An ERP system for sales manager who want to manage their sales, their customer relation, invoices and expenses.",
        "long_description": "",
        "media": [],
        "thumbnail": "/images/studio-agency/service_img_1.jpeg"
    },
    {
        "title": "Social Manager Fun",
        "slug": "smf",
        "link": "https://socialmanager.fun/",
        "technology": "Laravel, Bootstrap 4",
        "thirdy_party_api":"Social Media SDKs, Google cloud, Pusher",
        "platform": "website",
        "company": "Quickers Venture S.L",
        "short_description": "A SaaS platform for Social Media Marketer or Marketing Managing, who want to manage their social media posts in one platform",
        "long_description": "",
        "media": [],
        "thumbnail": "/images/studio-agency/service_img_1.jpeg"
    }
]

export {projects}